"""create layout_processing_jobs schema

Revision ID: 67f5f5b8299a
Revises: a407087c09ab
Create Date: 2026-07-31 21:44:57.191610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f5f5b8299a'
down_revision: Union[str, Sequence[str], None] = 'a407087c09ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('layout_source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_source_id'], ['layout_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_processing_jobs_layout_source_id'), 'layout_processing_jobs', ['layout_source_id'], unique=False)
    op.create_index(op.f('ix_layout_processing_jobs_project_id'), 'layout_processing_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_layout_processing_jobs_status'), 'layout_processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_layout_processing_jobs_status'), table_name='layout_processing_jobs')
    op.drop_index(op.f('ix_layout_processing_jobs_project_id'), table_name='layout_processing_jobs')
    op.drop_index(op.f('ix_layout_processing_jobs_layout_source_id'), table_name='layout_processing_jobs')
    op.drop_table('layout_processing_jobs')
    # ### end Alembic commands ###
