"""create layout_processing_artifacts schema

Revision ID: dc19e11ecd80
Revises: 67f5f5b8299a
Create Date: 2026-07-31 21:53:08.760539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc19e11ecd80'
down_revision: Union[str, Sequence[str], None] = '67f5f5b8299a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout_processing_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['layout_processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_processing_artifacts_artifact_type'), 'layout_processing_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_layout_processing_artifacts_job_id'), 'layout_processing_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_layout_processing_artifacts_project_id'), 'layout_processing_artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_layout_processing_artifacts_project_id'), table_name='layout_processing_artifacts')
    op.drop_index(op.f('ix_layout_processing_artifacts_job_id'), table_name='layout_processing_artifacts')
    op.drop_index(op.f('ix_layout_processing_artifacts_artifact_type'), table_name='layout_processing_artifacts')
    op.drop_table('layout_processing_artifacts')
    # ### end Alembic commands ###
